camel.karavan.project-id=karavan-test-1781736457
camel.karavan.project-name=karavan-test-1781736457
camel.karavan.project-description=karavan-test-1781736457
camel.jbang.gav=org.camel.karavan.demo:karavan-test-1781736457:1
camel.jbang.runtime=camel-main
camel.jbang.version=4.10.2
camel.jbang.dependencies=camel-console,camel-platform-http-main,camel:opentelemetry,camel:observability-services,agent:io.opentelemetry.javaagent:opentelemetry-javaagent:1.31.0
camel.jbang.jib-maven-plugin-version=3.4.4
camel.opentelemetry.enabled=true
camel.health.enabled=true
camel.health.exposure-level=full
camel.server.enabled=true
camel.server.healthCheckEnabled=true
camel.server.devConsoleEnabled=true
camel.main.name=karavan-test-1781736457
camel.main.tracingStandby=true
camel.main.autoConfigurationFailFast=false
camel.routecontroller.superviseEnabled=true
camel.routecontroller.backoffDelay=5000
camel.routecontroller.backoffMaxAttempts=100
camel.routecontroller.initialDelay=1000
camel.routecontroller.threadPoolSize=3
camel.context.dev-console=true
label.runtime=app.kubernetes.io/runtime
jib.from.image=gcr.io/distroless/java21-debian12@sha256:6e6a038d8763238480f7f7d50c55577fc9b6120a83ea11697b6e91159ad7ecba
jkube.version=1.18.1
jkube.skip.build=true
jkube.namespace=default
jkube.imagePullPolicy=Always
jkube.enricher.jkube-controller.type=Deployment
jkube.enricher.jkube-service.port=80:8080,443:8080
jkube.enricher.jkube-project-label.group=karavan
jkube.enricher.jkube-project-label.provider=karavan
jkube.enricher.jkube-well-known-labels.partOf=karavan-test-1781736457
jkube.recreate=true
server.port=9090
db.host=http://dev.dummy.db.com
